# Generated by Django 2.2.7 on 2019-11-24 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='質問')),
                ('date', models.DateTimeField(verbose_name='投稿日時')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問リスト',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, verbose_name='選択')),
                ('text', models.ForeignKey(default='bar', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cms.Question')),
            ],
            options={
                'verbose_name': '選択',
                'verbose_name_plural': '選択リスト',
            },
        ),
    ]
