# Generated by Django 2.2.7 on 2019-11-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20191124_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cms.Question'),
        ),
    ]
