# Generated by Django 2.2.7 on 2019-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_choice_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0, verbose_name='いいね！'),
        ),
    ]
