# Generated by Django 2.2.7 on 2019-11-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20191129_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-date_created'], 'verbose_name': 'いいね！', 'verbose_name_plural': 'いいね！リスト'},
        ),
    ]
