# Generated by Django 2.2.7 on 2020-02-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='締め切り'),
        ),
    ]
