# Generated by Django 2.2.7 on 2020-02-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_userinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
