# Generated by Django 2.2.7 on 2020-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200220_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='age',
            field=models.CharField(max_length=3, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(max_length=3, null=True, verbose_name='性別'),
        ),
    ]
