# Generated by Django 2.2.7 on 2020-03-08 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200307_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='secret',
            field=models.CharField(default='00', max_length=2, verbose_name='公開情報文字列'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(15)], verbose_name='年齢'),
        ),
    ]
